### ISSUE TITLE
Question about using this

### ISSUE THREAD

**Issue by psitem** [HeikoGr/chickencoop#1]
[Was this you, posting about replacing the Omlet coop door controller](https://community.home-assistant.io/t/omlet-auto-door-for-chicken-coop/191283/26)?

What voltage are you using for the motor and what did you use for the current-limiting resistor? 

Thanks!

**Comment by HeikoGr** [comment]
yes, this was me. unfortunately it's to dark outside to read the rings or use the multimeter (let alone: retrace my wiring...)

my plan was to write a BOM and a wiring plan as i redo the ugly temporary solution.
But like any temporary solution... well...

i will try to write you tomorrow. don't hesitate to bother me if I will forget you...

**Comment by HeikoGr** [comment]
I measured that I used an 10 ohm resistor.

As far as I can remember I used 10 ohm because 0,5 amp for the motor sounds reasonable (5v * 10ohm).

use this information at your own risk ⚠️

**Comment by psitem** [comment]
Appreciate the follow up! 

Decided that I want to emulate as closely as possible how the Omlet controller functions to ensure safety for my pets, so I've been mucking around with a DRV8833 motor controller and INA219 current sensor. The DRV8833 has a resistor that's supposed to work out to 1.2 A, and at the most aggressive sampling rate on the INA219 the motor hits nearly 1 A starting up and then stays under 125 mA.

I expect I'll post something on that HA community thread once I'm done playing and actually have something I can install on the coop.

**Comment by HeikoGr** [comment]
i think this will be the superiour solution, maybe i will hop-on when you finished :-D
